name: core
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.6.1
  collection: ^1.19.1
  crypto: ^3.0.6
  excel: ^4.0.6
  file_picker: ^10.1.9
  fl_chart: ^1.1.1
  flutter_svg: ^2.2.1
  google_fonts: ^6.3.0
  intl: ^0.20.2
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^11.1.0
  spreadsheet_decoder: ^2.3.0
  sqflite: ^2.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/branding/core/ui/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/branding/core/app_icon/core_appicon_full.png
  remove_alpha_ios: true
  min_sdk_android: 21

flutter_native_splash:
  color: "0F4D45"
  image: assets/branding/core/app_icon/core_appicon_foreground.png
  android: true
  ios: true
  web: false
  android_12:
    color: "0F4D45"
    image: assets/branding/core/app_icon/core_appicon_foreground.png
